name: Check compilers

on:
  # run every day at 06:00 UTC
  schedule:
    - cron: '0 6 * * *'
  # when triggered manually
  workflow_dispatch:
  # when auto merge is enabled (hack to make sure it's run before merging)
  pull_request:
    types: [auto_merge_enabled]

# Cancel "duplicated" workflows triggered by pushes to internal
# branches with associated PRs.
concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-check-compilers
  cancel-in-progress: true

jobs:
  CI-Cuda-Host:
    continue-on-error: true
    strategy:
      matrix:
        cxx: ['g++', 'clang++-20']
        cmake_build_type: ['Release', 'DbgNoSym']
        device: ['cuda', 'host']
        parallel: ['serial', 'mpi']
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/parthenon-hpc-lab/cuda12.8-mpi-hdf5-ascent
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: CMake
        run: |
          cmake -B builddir \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DMACHINE_CFG=${PWD}/cmake/machinecfg/GitHubActions.cmake \
            -DMACHINE_VARIANT=${{ matrix.device }}_${{ matrix.parallel }}
      - name: Build
        run: |
          cmake --build builddir --parallel 2
  CI-Rocm-HIP:
    continue-on-error: true
    strategy:
      matrix:
        cxx: ['hipcc']
        cmake_build_type: ['Release', 'DbgNoSym']
        device: ['hip']
        parallel: ['serial', 'mpi']
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/parthenon-hpc-lab/rocm6.2-mpi-hdf5
    env:
      CMAKE_GENERATOR: Ninja
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: CMake
        # Manually chaning the arch for this (debug) build as the
        # -O0 option causes compiler issue for the navi 1030 GPU at
        # compile time, see https://github.com/parthenon-hpc-lab/parthenon/pull/1191#issuecomment-2492035364
        run: |
          git config --global --add safe.directory $(pwd)
          cmake -B builddir \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            -DMACHINE_CFG=${PWD}/cmake/machinecfg/GitHubActions.cmake \
            -DMACHINE_VARIANT=${{ matrix.device }}_${{ matrix.parallel }} \
            -DKokkos_ARCH_AMD_GFX90A=ON -DKokkos_ARCH_NAVI1030=OFF
      - name: Build
        run: |
          cmake --build builddir --parallel 2
