name: Build and Deploy docs

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:
    types:
      - created

jobs:
    docs:
      name: build and deploy docs
      # not using latest due to issues with pip user packages, see
      # https://github.com/actions/runner-images/issues/10781 and
      # https://github.com/actions/runner-images/issues/10636
      runs-on: ubuntu-22.04

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            submodules: 'true'
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: install dependencies
          run: |
            pip install sphinx
            pip install sphinx-rtd-theme
            pip install sphinx-multiversion
            sudo apt install -y --force-yes -qq build-essential cmake
        - name: generate csv files
          run: |
            echo "Repo = ${GITHUB_REPOSITORY}"
            mkdir -p build && cd build
            cmake -DPARTHENON_DISABLE_HDF5=ON \
                  -DPARTHENON_DISABLE_MPI=ON \
                  -DREGRESSION_GOLD_STANDARD_SYNC=OFF \
                  -DBUILD_TESTING=OFF \
                  ..
            make -j4
            make param-docs
            cd ..
        - name: Check generated files for this branch are up to date
          run: |
            if git diff --exit-code -- doc/sphinx/src/generated/; then
              echo "Generated doc files up to date."
            else
              echo "Generated doc files not up to date. Run make param-docs and commit changes."
              exit 1
            fi
        - name: Get all git references, needed for sphinx multiversion
          run: |
            git fetch --prune --unshallow --tags
            git branch -a
            git tag --list
        - name: build docs
          run: |
            echo "Repo = ${GITHUB_REPOSITORY}"
            cd doc/sphinx
            # throw warnings as error to make sure docs properly build
            make multiversion SPHINXOPTS="-W --keep-going -n"
        - name: Deploy
          if: ${{ (github.event.pull_request.head.repo.full_name == github.repository) || (github.ref == 'refs/heads/develop') }}
          uses: peaceiris/actions-gh-pages@v3.7.3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./doc/sphinx/_build/html
            force_orphan: true
