#!/usr/bin/env python3
# =========================================================================================
# (C) (or copyright) 2020-2021. Triad National Security, LLC. All rights reserved.
#
# This program was produced under U.S. Government contract 89233218CNA000001 for Los
# Alamos National Laboratory (LANL), which is operated by Triad National Security, LLC
# for the U.S. Department of Energy/National Nuclear Security Administration. All rights
# in the program are reserved by Triad National Security, LLC, and the U.S. Department
# of Energy/National Nuclear Security Administration. The Government is granted for
# itself and others acting on its behalf a nonexclusive, paid-up, irrevocable worldwide
# license in this material to reproduce, prepare derivative works, distribute copies to
# the public, perform publicly and display publicly, and to permit others to do so.
# =========================================================================================

[build-system]
requires = ["hatchling>=1.21"]
build-backend = "hatchling.build"

[project]
name = "parthenon_tools"
version = "25.05.1"
description = "Python helper scripts to be used with Parthenon"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.9"
authors = [{ name = "The Parthenon collaboration", email = "jonahm@lanl.gov" }]
license = { file = "LICENSE.txt" }
keywords = ["simulations", "science", "computing", "githubapp"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Science/Research",
  "Environment :: Console",
  "Natural Language :: English",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
]
dependencies = [
  "h5py",
  "matplotlib",
  "numpy"
]

[project.scripts]
movie2d = "parthenon_tools.movie2d:main"
compute-asymmetry = "parthenon_tools.compute_asymmetry:main"
mergecsv = "parthenon_tools.mergecsv:main"
phdf-diff = "parthenon_tools.phdf_diff:main"
prettyparams = "parthenon_tools.prettyparams:main"
report-asymmetry = "parthenon_tools.report_asymmetry:main"

[project.urls]
Homepage = "https://github.com/lanl/parthenon/tree/develop/scripts/python/parthenon_tools"
Repository = "https://github.com/lanl/parthenon"
